### ISSUE TITLE
Bonds load incorrectly

### ISSUE THREAD

**Issue by brandhoff** [brands-d/kMap#71]
When a cube file containing simulated data is loaded the skeleton of the bonds is loaded with an offset.
I'm unsure weather this influences the Fouriertransformation.
I have attached a pictures of the imported cube-File in k-Map and one where it loads correctly in ase.
I have also attached said cube file.
Best regards

![skeleton](https://user-images.githubusercontent.com/7945263/183067398-dfaa399f-692e-4966-a50b-c7537c5e2d95.png)
![ase](https://user-images.githubusercontent.com/7945263/183067307-4f9dc3da-0f71-4cae-9a13-ff5b44f62d8e.PNG)
[Structure.zip](https://github.com/brands-d/kMap/files/9268124/Structure.zip)

**Comment by brands-d** [comment]
Thank you for the bug report!

I looked into it and the bonds do not load incorrectly as the origin in the cube file attached is not the center of the box. Thus, they appear shifted but it is actually the isosurfaces that were shifted to the center, not the bonds.

This should have no influence on the Fourier Transform because the shift happens at the plotting stage. Moreoever, a constant shift should only introduce a phase factor that cancels out anyways.

I will fix this soon after it gets decided whether we should automatically center everything first or not center anything at all.

**Comment by brands-d** [comment]
Issue resolved in commit 222448 and merged into all branches. Cube file will now be centered at loading time automatically.
